on:
  workflow_dispatch:

name: Build & Deploy

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run linting rules and tests
      uses: actions/setup-node@v3
    - run: npm install
    - run: npm run build

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        version: latest
        project_id: lauterbachandeilber
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@0.1.3
      with:
        path: build
        destination: lauterbachandeilber
